### ISSUE TITLE
Makefile.am

### ISSUE THREAD

**Issue by supremethememe** [lithiumtoast/pempo#4]
Can you post the same release with the Makefile.am included? Can't really make it without the Makefile.

**Comment by lithiumtoast** [comment]
You generate the makefile with CMake.

**Comment by supremethememe** [comment]
How do I make it with make? It says I need the Makefile.am to get the Makefile and Makefile.in

**Comment by supremethememe** [comment]
got it to work! The ext its weren't included so I manually added them and it built! Thank you for your help!
